# Pre-commit hooks configuration for EMBODIOS
# Install with: pre-commit install

repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Python code quality
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        files: ^src/|^tests/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=127', '--extend-ignore=E203,W503']
        files: ^src/|^tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports']
        files: ^src/embodi/
        additional_dependencies: ['types-PyYAML']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ['-ll', '-s', 'B404,B603,B607']
        files: ^src/|^tests/

  # Custom hooks for kernel code
  - repo: local
    hooks:
      - id: kernel-syntax-check
        name: Kernel C Syntax Check
        entry: bash -c 'cd kernel && for f in core/*.c mm/*.c lib/*.c; do gcc -fsyntax-only -I include -I include/arch/x86_64 "$f" || exit 1; done'
        language: system
        files: ^kernel/.*\.(c|h)$
        pass_filenames: false

      - id: kernel-header-check
        name: Kernel Header Guard Check
        entry: python3 scripts/check_header_guards.py
        language: system
        files: ^kernel/.*\.h$

      - id: kernel-unsafe-functions
        name: Check for unsafe C functions
        entry: bash -c 'if grep -r "\b(gets|sprintf)\b" kernel/ --include="*.c" --include="*.h"; then echo "Error: Unsafe functions found!"; exit 1; fi'
        language: system
        files: ^kernel/.*\.(c|h)$
        pass_filenames: false

      - id: kernel-tests
        name: Run kernel unit tests
        entry: bash -c 'cd kernel && make -f test.mk test'
        language: system
        files: ^kernel/.*\.(c|h)$
        pass_filenames: false

      - id: check-todo-completion
        name: Check TODO completion
        entry: bash -c 'if grep -r "TODO\|FIXME\|XXX" kernel/ --include="*.c" --include="*.h"; then echo "Warning: TODOs found"; fi'
        language: system
        files: ^kernel/.*\.(c|h)$
        pass_filenames: false

  # Documentation
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: ^docs/api/