/* EMBODIOS kernel-side Vulkan compute device layer.
 *
 * This is the kernel counterpart of tools/host_test_vulkan.c: it drives the
 * same hand-assembled SPIR-V compute shaders (kernel/ai/vk_shaders.h,
 * generated by tools/spirv_gen.py) for quantized matmul acceleration.
 *
 * Architecture:
 *   gpu_backend.c  — policy: probe cache, backend selection, CPU fallback
 *   vk_device.c    — device layer: PCI discovery, Vulkan instance/device
 *                    bring-up, buffer/descriptor/dispatch plumbing
 *
 * Status (v0.5.0 "Tesla"):
 *   - PCI discovery is real and runs at boot: VGA-class (0x03) devices and
 *     virtio-gpu (1af4:1010 transitional / 1af4:1050 modern) are enumerated
 *     and reported.
 *   - Actual Vulkan command submission requires a host-side Vulkan driver
 *     reachable from the guest. Under QEMU TCG there is none (no KVM, no
 *     Venus/virtio-gpu-vulkan), so vk_device_init() reports -VK_DEV_NO_DRIVER
 *     and the inference engine silently keeps the SIMD CPU path. See
 *     docs/gpu-backend.md for the activation path (virtio-gpu Venus or PCI
 *     passthrough) and the TODO markers in vk_device.c.
 */

#ifndef EMBODIOS_VK_DEVICE_H
#define EMBODIOS_VK_DEVICE_H

#include <embodios/types.h>

/* Result codes (negative = failure, 0 = success, positive = device count) */
#define VK_DEV_OK            0
#define VK_DEV_NO_DEVICE    (-1)  /* no GPU-class PCI device found */
#define VK_DEV_NO_DRIVER    (-2)  /* device present, no usable Vulkan driver */
#define VK_DEV_NO_MEMORY    (-3)  /* kernel memory allocation failed */
#define VK_DEV_BAD_SHADER   (-4)  /* embedded SPIR-V rejected */
#define VK_DEV_IO           (-5)  /* transport/command submission failure */
#define VK_DEV_UNSUPPORTED  (-6)  /* missing required device feature */

/* Candidate device found during PCI scan */
typedef struct vk_candidate {
    uint16_t vendor_id;
    uint16_t device_id;
    uint8_t  bus, device, function;
    uint8_t  class_code;
    uint8_t  subclass;
    int      is_virtio_gpu;    /* 1af4:1010/1050 — Venus activation path */
} vk_candidate_t;

#define VK_MAX_CANDIDATES 8

/* Scan the PCI bus for Vulkan-capable GPU candidates.
 * Returns the number of candidates (0 under QEMU TCG with default machine),
 * or a negative VK_DEV_* code if the PCI subsystem is not initialized.
 * The list (up to VK_MAX_CANDIDATES) is copied into `out` when non-NULL.
 * Idempotent; result is cached. */
int vk_device_probe(vk_candidate_t *out, int max_out);

/* Initialize the compute device: create Vulkan instance/device/queue, build
 * pipelines from the embedded SPIR-V (vk_shaders.h), allocate command
 * infrastructure.
 * Returns VK_DEV_OK on success, negative VK_DEV_* code otherwise.
 * Without a Venus/passthrough Vulkan driver this returns VK_DEV_NO_DRIVER;
 * callers must treat that as "use CPU fallback", not as an error. */
int vk_device_init(void);

/* 1 if vk_device_init() succeeded and dispatch is possible. */
int vk_device_available(void);

/* Human-readable name of the active device (or a static reason string when
 * unavailable). Never NULL. */
const char *vk_device_name(void);

/* C[m*n] = A[m*k] * B[k*n], fp32. Returns VK_DEV_OK or negative; on any
 * negative result the caller must fall back to the CPU path. */
int vk_matmul_f32(const float *A, const float *B, float *C,
                  uint32_t m, uint32_t k, uint32_t n);

/* C[m*n] = dequant_q8_0(A) * B[k*n]; A is ggml Q8_0 blocks (34 bytes per 32
 * values, fp16 scale + int8 quants), k must be a multiple of 32.
 * Returns VK_DEV_OK or negative; on any negative result the caller must
 * fall back to the CPU path. */
int vk_matmul_q8_0(const void *A, const float *B, float *C,
                   uint32_t m, uint32_t k, uint32_t n);

/* Shutdown (idempotent). */
void vk_device_shutdown(void);

#endif /* EMBODIOS_VK_DEVICE_H */
