/* Host-side validation of the embodiOS hand-assembled SPIR-V compute shaders.
 *
 * Runs kernel/ai/vk_shaders.h (generated by tools/spirv_gen.py) on the
 * lavapipe software Vulkan driver and compares against a CPU reference that
 * reuses the kernel's own dequant math (fp16->fp32 from
 * kernel/ai/gguf_inference.c).
 *
 * Build (from repo root):
 *     cc -O2 -Wall tools/host_test_vulkan.c -o tools/host_test_vulkan \
 *        -l:libvulkan.so.1 -lm
 * or simply:
 *     make -C tools vktest
 *
 * Run:
 *     tools/host_test_vulkan
 * (lavapipe is selected automatically via VK_ICD_FILENAMES unless the caller
 * already configured an ICD.)
 *
 * Pass criteria:
 *   matmul_f32 : max abs error < 1e-3  (identical accumulation order, so the
 *                expected value is actually ~0)
 *   matmul_q8_0: max relative error < 1e-2 (per-block dequant structure
 *                matches the kernel scalar dot product)
 */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "../kernel/ai/vk_shaders.h"

/* ============================================================================
 * Minimal Vulkan declarations (vulkan-dev headers are not installed in this
 * environment; link against libvulkan.so.1 directly). Only the core 1.0/1.1
 * surface used by this test is declared, with spec-exact struct layouts.
 * ========================================================================== */

#define VK_MAKE_API_VERSION(variant, major, minor, patch) \
    ((((uint32_t)(variant)) << 29U) | (((uint32_t)(major)) << 22U) | \
     (((uint32_t)(minor)) << 12U) | ((uint32_t)(patch)))
#define VK_API_VERSION_1_1 VK_MAKE_API_VERSION(0, 1, 1, 0)

typedef uint32_t VkFlags;
typedef uint32_t VkBool32;
typedef uint64_t VkDeviceSize;
typedef struct VkInstance_T *VkInstance;
typedef struct VkPhysicalDevice_T *VkPhysicalDevice;
typedef struct VkDevice_T *VkDevice;
typedef struct VkQueue_T *VkQueue;
typedef struct VkCommandBuffer_T *VkCommandBuffer;
typedef uint64_t VkDeviceMemory;
typedef uint64_t VkBuffer;
typedef uint64_t VkShaderModule;
typedef uint64_t VkDescriptorSetLayout;
typedef uint64_t VkPipelineLayout;
typedef uint64_t VkPipeline;
typedef uint64_t VkDescriptorPool;
typedef uint64_t VkDescriptorSet;
typedef uint64_t VkCommandPool;

typedef enum VkResult {
    VK_SUCCESS = 0,
    VK_INCOMPLETE = 5,
    VK_ERROR_OUT_OF_HOST_MEMORY = -1,
    VK_ERROR_OUT_OF_DEVICE_MEMORY = -2,
    VK_ERROR_INITIALIZATION_FAILED = -3,
} VkResult;

typedef enum VkStructureType {
    VK_STRUCTURE_TYPE_APPLICATION_INFO = 0,
    VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO = 1,
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO = 2,
    VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO = 3,
    VK_STRUCTURE_TYPE_SUBMIT_INFO = 4,
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO = 5,
    VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO = 12,
    VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO = 16,
    VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO = 18,
    VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO = 29,
    VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO = 30,
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO = 32,
    VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO = 33,
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO = 34,
    VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET = 35,
    VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO = 39,
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO = 40,
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO = 42,
} VkStructureType;

typedef enum VkDescriptorType {
    VK_DESCRIPTOR_TYPE_STORAGE_BUFFER = 7,
} VkDescriptorType;

#define VK_QUEUE_COMPUTE_BIT                0x00000002u
#define VK_SHADER_STAGE_COMPUTE_BIT         0x00000020u
#define VK_BUFFER_USAGE_STORAGE_BUFFER_BIT  0x00000020u
#define VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT 0x00000002u
#define VK_MEMORY_PROPERTY_HOST_COHERENT_BIT 0x00000004u
#define VK_PIPELINE_BIND_POINT_COMPUTE      1
#define VK_SHARING_MODE_EXCLUSIVE           0
#define VK_WHOLE_SIZE                       (~0ULL)

typedef struct VkApplicationInfo {
    VkStructureType sType;
    const void *pNext;
    const char *pApplicationName;
    uint32_t applicationVersion;
    const char *pEngineName;
    uint32_t engineVersion;
    uint32_t apiVersion;
} VkApplicationInfo;

typedef struct VkInstanceCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    const VkApplicationInfo *pApplicationInfo;
    uint32_t enabledLayerCount;
    const char *const *ppEnabledLayerNames;
    uint32_t enabledExtensionCount;
    const char *const *ppEnabledExtensionNames;
} VkInstanceCreateInfo;

typedef struct VkPhysicalDeviceProperties {
    uint32_t apiVersion;
    uint32_t driverVersion;
    uint32_t vendorID;
    uint32_t deviceID;
    uint32_t deviceType;
    char deviceName[256];
    uint8_t pipelineCacheUUID[16];
    /* limits + sparseProperties follow in the real struct; sized generously
     * so the driver can write the full structure without overflow. */
    uint8_t _tail[2048];
} VkPhysicalDeviceProperties;

typedef struct VkExtent3D { uint32_t width, height, depth; } VkExtent3D;

typedef struct VkQueueFamilyProperties {
    VkFlags queueFlags;
    uint32_t queueCount;
    uint32_t timestampValidBits;
    VkExtent3D minImageTransferGranularity;
} VkQueueFamilyProperties;

typedef struct VkMemoryType {
    VkFlags propertyFlags;
    uint32_t heapIndex;
} VkMemoryType;

typedef struct VkMemoryHeap {
    VkDeviceSize size;
    VkFlags flags;
} VkMemoryHeap;

typedef struct VkPhysicalDeviceMemoryProperties {
    uint32_t memoryTypeCount;
    VkMemoryType memoryTypes[32];
    uint32_t memoryHeapCount;
    VkMemoryHeap memoryHeaps[16];
} VkPhysicalDeviceMemoryProperties;

typedef struct VkDeviceQueueCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    uint32_t queueFamilyIndex;
    uint32_t queueCount;
    const float *pQueuePriorities;
} VkDeviceQueueCreateInfo;

typedef struct VkDeviceCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    uint32_t queueCreateInfoCount;
    const VkDeviceQueueCreateInfo *pQueueCreateInfos;
    uint32_t enabledLayerCount;
    const char *const *ppEnabledLayerNames;
    uint32_t enabledExtensionCount;
    const char *const *ppEnabledExtensionNames;
    const void *pEnabledFeatures;
} VkDeviceCreateInfo;

typedef struct VkMemoryRequirements {
    VkDeviceSize size;
    VkDeviceSize alignment;
    uint32_t memoryTypeBits;
} VkMemoryRequirements;

typedef struct VkMemoryAllocateInfo {
    VkStructureType sType;
    const void *pNext;
    VkDeviceSize allocationSize;
    uint32_t memoryTypeIndex;
} VkMemoryAllocateInfo;

typedef struct VkBufferCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    VkDeviceSize size;
    VkFlags usage;
    uint32_t sharingMode;
    uint32_t queueFamilyIndexCount;
    const uint32_t *pQueueFamilyIndices;
} VkBufferCreateInfo;

typedef struct VkShaderModuleCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    size_t codeSize;
    const uint32_t *pCode;
} VkShaderModuleCreateInfo;

typedef struct VkDescriptorSetLayoutBinding {
    uint32_t binding;
    VkDescriptorType descriptorType;
    uint32_t descriptorCount;
    VkFlags stageFlags;
    const void *pImmutableSamplers;
} VkDescriptorSetLayoutBinding;

typedef struct VkDescriptorSetLayoutCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    uint32_t bindingCount;
    const VkDescriptorSetLayoutBinding *pBindings;
} VkDescriptorSetLayoutCreateInfo;

typedef struct VkPushConstantRange {
    VkFlags stageFlags;
    uint32_t offset;
    uint32_t size;
} VkPushConstantRange;

typedef struct VkPipelineLayoutCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    uint32_t setLayoutCount;
    const VkDescriptorSetLayout *pSetLayouts;
    uint32_t pushConstantRangeCount;
    const VkPushConstantRange *pPushConstantRanges;
} VkPipelineLayoutCreateInfo;

typedef struct VkPipelineShaderStageCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    VkFlags stage;
    VkShaderModule module;
    const char *pName;
    const void *pSpecializationInfo;
} VkPipelineShaderStageCreateInfo;

typedef struct VkComputePipelineCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    VkPipelineShaderStageCreateInfo stage;
    VkPipelineLayout layout;
    uint64_t basePipelineHandle;
    int32_t basePipelineIndex;
} VkComputePipelineCreateInfo;

typedef struct VkDescriptorPoolSize {
    VkDescriptorType type;
    uint32_t descriptorCount;
} VkDescriptorPoolSize;

typedef struct VkDescriptorPoolCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    uint32_t maxSets;
    uint32_t poolSizeCount;
    const VkDescriptorPoolSize *pPoolSizes;
} VkDescriptorPoolCreateInfo;

typedef struct VkDescriptorSetAllocateInfo {
    VkStructureType sType;
    const void *pNext;
    VkDescriptorPool descriptorPool;
    uint32_t descriptorSetCount;
    const VkDescriptorSetLayout *pSetLayouts;
} VkDescriptorSetAllocateInfo;

typedef struct VkDescriptorBufferInfo {
    VkBuffer buffer;
    VkDeviceSize offset;
    VkDeviceSize range;
} VkDescriptorBufferInfo;

typedef struct VkWriteDescriptorSet {
    VkStructureType sType;
    const void *pNext;
    VkDescriptorSet dstSet;
    uint32_t dstBinding;
    uint32_t dstArrayElement;
    uint32_t descriptorCount;
    VkDescriptorType descriptorType;
    const void *pImageInfo;
    const VkDescriptorBufferInfo *pBufferInfo;
    const void *pTexelBufferView;
} VkWriteDescriptorSet;

typedef struct VkCommandPoolCreateInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    uint32_t queueFamilyIndex;
} VkCommandPoolCreateInfo;

typedef struct VkCommandBufferAllocateInfo {
    VkStructureType sType;
    const void *pNext;
    VkCommandPool commandPool;
    uint32_t level; /* 0 = PRIMARY */
    uint32_t commandBufferCount;
} VkCommandBufferAllocateInfo;

typedef struct VkCommandBufferBeginInfo {
    VkStructureType sType;
    const void *pNext;
    VkFlags flags;
    const void *pInheritanceInfo;
} VkCommandBufferBeginInfo;

typedef struct VkSubmitInfo {
    VkStructureType sType;
    const void *pNext;
    uint32_t waitSemaphoreCount;
    const void *pWaitSemaphores;
    const void *pWaitDstStageMask;
    uint32_t commandBufferCount;
    const VkCommandBuffer *pCommandBuffers;
    uint32_t signalSemaphoreCount;
    const void *pSignalSemaphores;
} VkSubmitInfo;

/* Function prototypes (exported by libvulkan.so.1) */
VkResult vkCreateInstance(const VkInstanceCreateInfo *, const void *, VkInstance *);
void vkDestroyInstance(VkInstance, const void *);
VkResult vkEnumeratePhysicalDevices(VkInstance, uint32_t *, VkPhysicalDevice *);
void vkGetPhysicalDeviceProperties(VkPhysicalDevice, VkPhysicalDeviceProperties *);
void vkGetPhysicalDeviceQueueFamilyProperties(VkPhysicalDevice, uint32_t *,
                                              VkQueueFamilyProperties *);
void vkGetPhysicalDeviceMemoryProperties(VkPhysicalDevice,
                                         VkPhysicalDeviceMemoryProperties *);
VkResult vkCreateDevice(VkPhysicalDevice, const VkDeviceCreateInfo *,
                        const void *, VkDevice *);
void vkDestroyDevice(VkDevice, const void *);
void vkGetDeviceQueue(VkDevice, uint32_t, uint32_t, VkQueue *);
VkResult vkCreateBuffer(VkDevice, const VkBufferCreateInfo *, const void *,
                        VkBuffer *);
void vkDestroyBuffer(VkDevice, VkBuffer, const void *);
void vkGetBufferMemoryRequirements(VkDevice, VkBuffer, VkMemoryRequirements *);
VkResult vkAllocateMemory(VkDevice, const VkMemoryAllocateInfo *, const void *,
                          VkDeviceMemory *);
void vkFreeMemory(VkDevice, VkDeviceMemory, const void *);
VkResult vkBindBufferMemory(VkDevice, VkBuffer, VkDeviceMemory, VkDeviceSize);
VkResult vkMapMemory(VkDevice, VkDeviceMemory, VkDeviceSize, VkDeviceSize,
                     VkFlags, void **);
void vkUnmapMemory(VkDevice, VkDeviceMemory);
VkResult vkCreateShaderModule(VkDevice, const VkShaderModuleCreateInfo *,
                              const void *, VkShaderModule *);
void vkDestroyShaderModule(VkDevice, VkShaderModule, const void *);
VkResult vkCreateDescriptorSetLayout(VkDevice,
                                     const VkDescriptorSetLayoutCreateInfo *,
                                     const void *, VkDescriptorSetLayout *);
VkResult vkCreatePipelineLayout(VkDevice, const VkPipelineLayoutCreateInfo *,
                                const void *, VkPipelineLayout *);
VkResult vkCreateComputePipelines(VkDevice, uint64_t, uint32_t,
                                  const VkComputePipelineCreateInfo *,
                                  const void *, VkPipeline *);
void vkDestroyPipeline(VkDevice, VkPipeline, const void *);
VkResult vkCreateDescriptorPool(VkDevice, const VkDescriptorPoolCreateInfo *,
                                const void *, VkDescriptorPool *);
VkResult vkAllocateDescriptorSets(VkDevice, const VkDescriptorSetAllocateInfo *,
                                  VkDescriptorSet *);
void vkUpdateDescriptorSets(VkDevice, uint32_t, const VkWriteDescriptorSet *,
                            uint32_t, const void *);
VkResult vkCreateCommandPool(VkDevice, const VkCommandPoolCreateInfo *,
                             const void *, VkCommandPool *);
VkResult vkAllocateCommandBuffers(VkDevice, const VkCommandBufferAllocateInfo *,
                                  VkCommandBuffer *);
VkResult vkBeginCommandBuffer(VkCommandBuffer,
                              const VkCommandBufferBeginInfo *);
void vkCmdBindPipeline(VkCommandBuffer, uint32_t, VkPipeline);
void vkCmdBindDescriptorSets(VkCommandBuffer, uint32_t, VkPipelineLayout,
                             uint32_t, uint32_t, const VkDescriptorSet *,
                             uint32_t, const uint32_t *);
void vkCmdPushConstants(VkCommandBuffer, VkPipelineLayout, VkFlags, uint32_t,
                        uint32_t, const void *);
void vkCmdDispatch(VkCommandBuffer, uint32_t, uint32_t, uint32_t);
VkResult vkEndCommandBuffer(VkCommandBuffer);
VkResult vkQueueSubmit(VkQueue, uint32_t, const VkSubmitInfo *, uint64_t);
VkResult vkQueueWaitIdle(VkQueue);

/* ============================================================================
 * fp16 helpers — math mirrored from kernel/ai/gguf_inference.c
 * ========================================================================== */

static float fp16_to_fp32(uint16_t h)
{
    uint32_t sign = (h >> 15) & 1;
    uint32_t exp = (h >> 10) & 0x1f;
    uint32_t mant = h & 0x3ff;
    uint32_t f;

    if (exp == 0) {
        if (mant == 0) {
            f = sign << 31;
        } else {
            exp = 1;
            while (!(mant & 0x400)) {
                mant <<= 1;
                exp--;
            }
            mant &= 0x3ff;
            f = (sign << 31) | ((exp + 127 - 15) << 23) | (mant << 13);
        }
    } else if (exp == 31) {
        f = (sign << 31) | 0x7f800000 | (mant << 13);
    } else {
        f = (sign << 31) | ((exp + 127 - 15) << 23) | (mant << 13);
    }

    union { uint32_t i; float f; } u;
    u.i = f;
    return u.f;
}

static uint16_t fp32_to_fp16(float f)
{
    union { float f; uint32_t i; } u;
    u.f = f;
    uint32_t x = u.i;
    uint32_t sign = (x >> 16) & 0x8000;
    int exp = (int)((x >> 23) & 0xff) - 127 + 15;
    uint32_t mant = x & 0x7fffff;

    if (exp <= 0) {
        /* underflow to zero/denormal (good enough for test scales) */
        if (exp < -10)
            return (uint16_t)sign;
        mant |= 0x800000;
        uint32_t denorm = mant >> (14 - exp);
        return (uint16_t)(sign | denorm);
    }
    if (exp >= 31)
        return (uint16_t)(sign | 0x7c00); /* inf */
    return (uint16_t)(sign | ((uint32_t)exp << 10) | (mant >> 13));
}

/* ============================================================================
 * ggml Q8_0 block (34 bytes): fp16 scale + 32 x int8
 * ========================================================================== */

#define QK8_0 32
#define Q8_0_BLOCK_BYTES 34

typedef struct __attribute__((packed)) {
    uint16_t d;
    int8_t qs[QK8_0];
} block_q8_0;

/* ggml-style row quantizer (positive scale variant) */
static void quantize_row_q8_0(const float *x, block_q8_0 *blocks, int k)
{
    int nb = k / QK8_0;
    for (int b = 0; b < nb; b++) {
        float amax = 0.0f;
        for (int j = 0; j < QK8_0; j++) {
            float v = fabsf(x[b * QK8_0 + j]);
            if (v > amax)
                amax = v;
        }
        float d = amax / 127.0f;
        uint16_t d16 = fp32_to_fp16(d);
        float d_deq = fp16_to_fp32(d16);
        blocks[b].d = d16;
        if (d_deq == 0.0f) {
            memset(blocks[b].qs, 0, QK8_0);
            continue;
        }
        float id = 1.0f / d_deq;
        for (int j = 0; j < QK8_0; j++) {
            float q = roundf(x[b * QK8_0 + j] * id);
            if (q > 127.0f)
                q = 127.0f;
            if (q < -127.0f)
                q = -127.0f;
            blocks[b].qs[j] = (int8_t)q;
        }
    }
}

/* ============================================================================
 * Deterministic PRNG (splitmix64)
 * ========================================================================== */

static uint64_t g_rng_state;

static uint64_t rng_next(void)
{
    uint64_t z = (g_rng_state += 0x9E3779B97F4A7C15ULL);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

static float rng_float(void) /* uniform in [-1, 1] */
{
    return ((double)(rng_next() >> 11) / (double)(1ULL << 53)) * 2.0f - 1.0f;
}

/* ============================================================================
 * CPU references
 * ========================================================================== */

static void matmul_f32_ref(const float *A, const float *B, float *C,
                           uint32_t m, uint32_t k, uint32_t n)
{
    for (uint32_t i = 0; i < m; i++) {
        for (uint32_t j = 0; j < n; j++) {
            float acc = 0.0f;
            for (uint32_t kk = 0; kk < k; kk++)
                acc += A[i * k + kk] * B[kk * n + j];
            C[i * n + j] = acc;
        }
    }
}

/* Dequant-in-dot structure matching kernel vec_dot_q8_0 style accumulation:
 * per-block fp32 partial sum scaled by d, accumulated across blocks. */
static void matmul_q8_0_ref(const block_q8_0 *A, const float *B, float *C,
                            uint32_t m, uint32_t k, uint32_t n)
{
    uint32_t nb = k / QK8_0;
    for (uint32_t i = 0; i < m; i++) {
        for (uint32_t j = 0; j < n; j++) {
            float acc = 0.0f;
            for (uint32_t b = 0; b < nb; b++) {
                const block_q8_0 *blk = &A[i * nb + b];
                float d = fp16_to_fp32(blk->d);
                float bacc = 0.0f;
                for (uint32_t jj = 0; jj < QK8_0; jj++)
                    bacc += (float)blk->qs[jj] * B[(b * QK8_0 + jj) * n + j];
                acc += d * bacc;
            }
            C[i * n + j] = acc;
        }
    }
}

/* ============================================================================
 * Vulkan test rig
 * ========================================================================== */

#define VK_CHECK(expr)                                                  \
    do {                                                                \
        VkResult _r = (expr);                                           \
        if (_r != VK_SUCCESS) {                                         \
            fprintf(stderr, "FATAL: %s failed: VkResult %d (%s:%d)\n",  \
                    #expr, (int)_r, __FILE__, __LINE__);                \
            exit(2);                                                    \
        }                                                               \
    } while (0)

struct vk_ctx {
    VkInstance instance;
    VkPhysicalDevice phys;
    uint32_t queue_family;
    VkDevice device;
    VkQueue queue;
    uint32_t mem_type_index;
    VkDescriptorSetLayout set_layout;
    VkPipelineLayout pipeline_layout;
    VkDescriptorPool desc_pool;
    VkCommandPool cmd_pool;
};

struct vk_buf {
    VkBuffer buffer;
    VkDeviceMemory memory;
    VkDeviceSize size;
};

static void vk_ctx_init(struct vk_ctx *c)
{
    memset(c, 0, sizeof(*c));

    /* Prefer lavapipe unless the caller pinned a different ICD. */
    if (!getenv("VK_ICD_FILENAMES") && !getenv("VK_DRIVER_FILES") &&
        !getenv("VK_LOADER_DRIVERS_SELECT")) {
        setenv("VK_ICD_FILENAMES",
               "/usr/share/vulkan/icd.d/lvp_icd.x86_64.json", 0);
    }

    VkApplicationInfo app = {
        .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
        .pApplicationName = "embodios-host-test-vulkan",
        .applicationVersion = 1,
        .pEngineName = "embodios",
        .engineVersion = 1,
        .apiVersion = VK_API_VERSION_1_1,
    };
    VkInstanceCreateInfo ici = {
        .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
        .pApplicationInfo = &app,
    };
    VK_CHECK(vkCreateInstance(&ici, NULL, &c->instance));

    uint32_t dev_count = 0;
    VK_CHECK(vkEnumeratePhysicalDevices(c->instance, &dev_count, NULL));
    if (dev_count == 0) {
        fprintf(stderr, "FATAL: no Vulkan physical devices\n");
        exit(2);
    }
    VkPhysicalDevice *devs = calloc(dev_count, sizeof(*devs));
    VK_CHECK(vkEnumeratePhysicalDevices(c->instance, &dev_count, devs));

    /* Pick the first device exposing a compute queue family. */
    int found = 0;
    for (uint32_t d = 0; d < dev_count && !found; d++) {
        uint32_t qf_count = 0;
        vkGetPhysicalDeviceQueueFamilyProperties(devs[d], &qf_count, NULL);
        VkQueueFamilyProperties *qfs = calloc(qf_count, sizeof(*qfs));
        vkGetPhysicalDeviceQueueFamilyProperties(devs[d], &qf_count, qfs);
        for (uint32_t q = 0; q < qf_count; q++) {
            if (qfs[q].queueFlags & VK_QUEUE_COMPUTE_BIT) {
                c->phys = devs[d];
                c->queue_family = q;
                found = 1;
                break;
            }
        }
        free(qfs);
    }
    free(devs);
    if (!found) {
        fprintf(stderr, "FATAL: no device with a compute queue\n");
        exit(2);
    }

    VkPhysicalDeviceProperties props;
    vkGetPhysicalDeviceProperties(c->phys, &props);
    printf("device: %s (vendorID 0x%04x, deviceID 0x%04x, type %u, api %u.%u)\n",
           props.deviceName, props.vendorID, props.deviceID, props.deviceType,
           (props.apiVersion >> 22) & 0x3ff, (props.apiVersion >> 12) & 0x3ff);

    float prio = 1.0f;
    VkDeviceQueueCreateInfo qci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
        .queueFamilyIndex = c->queue_family,
        .queueCount = 1,
        .pQueuePriorities = &prio,
    };
    VkDeviceCreateInfo dci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
        .queueCreateInfoCount = 1,
        .pQueueCreateInfos = &qci,
    };
    VK_CHECK(vkCreateDevice(c->phys, &dci, NULL, &c->device));
    vkGetDeviceQueue(c->device, c->queue_family, 0, &c->queue);

    /* host-visible + coherent memory type */
    VkPhysicalDeviceMemoryProperties mp;
    vkGetPhysicalDeviceMemoryProperties(c->phys, &mp);
    uint32_t want = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
    c->mem_type_index = UINT32_MAX;
    for (uint32_t t = 0; t < mp.memoryTypeCount; t++) {
        if ((mp.memoryTypes[t].propertyFlags & want) == want) {
            c->mem_type_index = t;
            break;
        }
    }
    if (c->mem_type_index == UINT32_MAX) {
        fprintf(stderr, "FATAL: no host-visible coherent memory type\n");
        exit(2);
    }

    /* descriptor set layout: 3 storage buffers (A, B, C) */
    VkDescriptorSetLayoutBinding bindings[3];
    for (int b = 0; b < 3; b++) {
        bindings[b].binding = (uint32_t)b;
        bindings[b].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[b].descriptorCount = 1;
        bindings[b].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
        bindings[b].pImmutableSamplers = NULL;
    }
    VkDescriptorSetLayoutCreateInfo slci = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 3,
        .pBindings = bindings,
    };
    VK_CHECK(vkCreateDescriptorSetLayout(c->device, &slci, NULL,
                                         &c->set_layout));

    VkPushConstantRange pc_range = {
        .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        .offset = 0,
        .size = 12, /* u32 m, k, n */
    };
    VkPipelineLayoutCreateInfo plci = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts = &c->set_layout,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &pc_range,
    };
    VK_CHECK(vkCreatePipelineLayout(c->device, &plci, NULL,
                                    &c->pipeline_layout));

    VkDescriptorPoolSize pool_size = {
        .type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
        .descriptorCount = 64,
    };
    VkDescriptorPoolCreateInfo dpci = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .maxSets = 16,
        .poolSizeCount = 1,
        .pPoolSizes = &pool_size,
    };
    VK_CHECK(vkCreateDescriptorPool(c->device, &dpci, NULL, &c->desc_pool));

    VkCommandPoolCreateInfo cpci = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        .queueFamilyIndex = c->queue_family,
    };
    VK_CHECK(vkCreateCommandPool(c->device, &cpci, NULL, &c->cmd_pool));
}

static struct vk_buf vk_buf_create(struct vk_ctx *c, VkDeviceSize size)
{
    struct vk_buf b;
    b.size = size;
    VkBufferCreateInfo bci = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
        .size = size,
        .usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
    };
    VK_CHECK(vkCreateBuffer(c->device, &bci, NULL, &b.buffer));
    VkMemoryRequirements req;
    vkGetBufferMemoryRequirements(c->device, b.buffer, &req);
    if (!(req.memoryTypeBits & (1u << c->mem_type_index))) {
        fprintf(stderr, "FATAL: buffer not bindable to memory type %u\n",
                c->mem_type_index);
        exit(2);
    }
    VkMemoryAllocateInfo mai = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize = req.size,
        .memoryTypeIndex = c->mem_type_index,
    };
    VK_CHECK(vkAllocateMemory(c->device, &mai, NULL, &b.memory));
    VK_CHECK(vkBindBufferMemory(c->device, b.buffer, b.memory, 0));
    return b;
}

static void vk_buf_destroy(struct vk_ctx *c, struct vk_buf *b)
{
    vkDestroyBuffer(c->device, b->buffer, NULL);
    vkFreeMemory(c->device, b->memory, NULL);
}

static void *vk_buf_map(struct vk_ctx *c, struct vk_buf *b)
{
    void *p = NULL;
    VK_CHECK(vkMapMemory(c->device, b->memory, 0, b->size, 0, &p));
    return p;
}

static VkPipeline vk_create_pipeline(struct vk_ctx *c, const uint32_t *code,
                                     uint32_t word_count)
{
    VkShaderModuleCreateInfo smci = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = (size_t)word_count * 4,
        .pCode = code,
    };
    VkShaderModule shader;
    VK_CHECK(vkCreateShaderModule(c->device, &smci, NULL, &shader));

    VkComputePipelineCreateInfo cpci = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage = VK_SHADER_STAGE_COMPUTE_BIT,
            .module = shader,
            .pName = "main",
        },
        .layout = c->pipeline_layout,
    };
    VkPipeline pipeline;
    VK_CHECK(vkCreateComputePipelines(c->device, 0, 1, &cpci, NULL, &pipeline));
    vkDestroyShaderModule(c->device, shader, NULL);
    return pipeline;
}

/* Run one compute matmul: A (a_bytes), B (fp32 k*n), C (fp32 m*n).
 *
 * The A buffer is rounded up to a 4-byte multiple (tail zero-filled):
 * matmul_q8_0 reads whole u32 words and the final word of the last 34-byte
 * Q8_0 block can otherwise straddle the buffer end (out-of-bounds SSBO
 * read). The kernel driver applies the same padding when uploading weights. */
static void vk_run_matmul(struct vk_ctx *c, VkPipeline pipeline,
                          const void *a_data, VkDeviceSize a_bytes,
                          const float *b_data, const float *c_fill,
                          float *c_out,
                          uint32_t m, uint32_t k, uint32_t n)
{
    VkDeviceSize a_alloc = (a_bytes + 3) & ~3ULL;
    struct vk_buf ba = vk_buf_create(c, a_alloc);
    struct vk_buf bb = vk_buf_create(c, (VkDeviceSize)k * n * 4);
    struct vk_buf bc = vk_buf_create(c, (VkDeviceSize)m * n * 4);

    void *pa = vk_buf_map(c, &ba);
    memcpy(pa, a_data, a_bytes);
    memset((char *)pa + a_bytes, 0, a_alloc - a_bytes);
    vkUnmapMemory(c->device, ba.memory);
    memcpy(vk_buf_map(c, &bb), b_data, (size_t)k * n * 4);
    vkUnmapMemory(c->device, bb.memory);
    memcpy(vk_buf_map(c, &bc), c_fill, (size_t)m * n * 4);
    vkUnmapMemory(c->device, bc.memory);

    VkDescriptorSetAllocateInfo dsai = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool = c->desc_pool,
        .descriptorSetCount = 1,
        .pSetLayouts = &c->set_layout,
    };
    VkDescriptorSet dset;
    VK_CHECK(vkAllocateDescriptorSets(c->device, &dsai, &dset));

    VkDescriptorBufferInfo infos[3] = {
        { ba.buffer, 0, VK_WHOLE_SIZE },
        { bb.buffer, 0, VK_WHOLE_SIZE },
        { bc.buffer, 0, VK_WHOLE_SIZE },
    };
    VkWriteDescriptorSet writes[3];
    for (int w = 0; w < 3; w++) {
        memset(&writes[w], 0, sizeof(writes[w]));
        writes[w].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[w].dstSet = dset;
        writes[w].dstBinding = (uint32_t)w;
        writes[w].descriptorCount = 1;
        writes[w].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[w].pBufferInfo = &infos[w];
    }
    vkUpdateDescriptorSets(c->device, 3, writes, 0, NULL);

    VkCommandBufferAllocateInfo cbai = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = c->cmd_pool,
        .level = 0,
        .commandBufferCount = 1,
    };
    VkCommandBuffer cmd;
    VK_CHECK(vkAllocateCommandBuffers(c->device, &cbai, &cmd));

    VkCommandBufferBeginInfo cbbi = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
    };
    VK_CHECK(vkBeginCommandBuffer(cmd, &cbbi));
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            c->pipeline_layout, 0, 1, &dset, 0, NULL);
    uint32_t pc[3] = { m, k, n };
    vkCmdPushConstants(cmd, c->pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), pc);
    uint32_t groups = (m * n + 63) / 64;
    vkCmdDispatch(cmd, groups, 1, 1);
    VK_CHECK(vkEndCommandBuffer(cmd));

    VkSubmitInfo si = {
        .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .commandBufferCount = 1,
        .pCommandBuffers = &cmd,
    };
    VK_CHECK(vkQueueSubmit(c->queue, 1, &si, 0));
    VK_CHECK(vkQueueWaitIdle(c->queue));

    memcpy(c_out, vk_buf_map(c, &bc), (size_t)m * n * 4);
    vkUnmapMemory(c->device, bc.memory);

    vk_buf_destroy(c, &ba);
    vk_buf_destroy(c, &bb);
    vk_buf_destroy(c, &bc);
}

/* ============================================================================
 * Test cases
 * ========================================================================== */

static int test_matmul_f32(struct vk_ctx *c, VkPipeline pipeline,
                           uint32_t m, uint32_t k, uint32_t n)
{
    float *A = malloc((size_t)m * k * 4);
    float *B = malloc((size_t)k * n * 4);
    float *C_gpu = malloc((size_t)m * n * 4);
    float *C_ref = malloc((size_t)m * n * 4);
    float *C_fill = malloc((size_t)m * n * 4);

    for (uint32_t i = 0; i < m * k; i++)
        A[i] = rng_float();
    for (uint32_t i = 0; i < k * n; i++)
        B[i] = rng_float();
    for (uint32_t i = 0; i < m * n; i++)
        C_fill[i] = -999.0f; /* sentinel: shader must overwrite every element */

    matmul_f32_ref(A, B, C_ref, m, k, n);
    vk_run_matmul(c, pipeline, A, (VkDeviceSize)m * k * 4, B, C_fill, C_gpu,
                  m, k, n);

    double max_abs = 0.0, max_rel = 0.0;
    for (uint32_t i = 0; i < m * n; i++) {
        double err = fabs((double)C_gpu[i] - (double)C_ref[i]);
        double denom = fabs((double)C_ref[i]) > 1e-6 ? fabs((double)C_ref[i]) : 1.0;
        if (err > max_abs)
            max_abs = err;
        if (err / denom > max_rel)
            max_rel = err / denom;
    }

    int pass = max_abs < 1e-3;
    printf("matmul_f32  %3ux%-3ux%-3u : max_abs_err=%.3g max_rel_err=%.3g -> %s\n",
           m, k, n, max_abs, max_rel, pass ? "PASS" : "FAIL");

    free(A); free(B); free(C_gpu); free(C_ref); free(C_fill);
    return pass;
}

static int test_matmul_q8_0(struct vk_ctx *c, VkPipeline pipeline,
                            uint32_t m, uint32_t k, uint32_t n)
{
    uint32_t nb = k / QK8_0;
    size_t a_elems = (size_t)m * k;
    size_t a_blocks = (size_t)m * nb;
    float *A_f32 = malloc(a_elems * 4);
    block_q8_0 *A_q8 = malloc(a_blocks * sizeof(block_q8_0));
    float *B = malloc((size_t)k * n * 4);
    float *C_gpu = malloc((size_t)m * n * 4);
    float *C_ref = malloc((size_t)m * n * 4);
    float *C_fill = malloc((size_t)m * n * 4);

    for (size_t i = 0; i < a_elems; i++)
        A_f32[i] = rng_float() * 3.0f; /* exercise a wider fp16 scale range */
    for (uint32_t i = 0; i < k * n; i++)
        B[i] = rng_float();
    for (uint32_t i = 0; i < m * n; i++)
        C_fill[i] = -999.0f;

    for (uint32_t i = 0; i < m; i++)
        quantize_row_q8_0(A_f32 + (size_t)i * k, A_q8 + (size_t)i * nb, (int)k);

    matmul_q8_0_ref(A_q8, B, C_ref, m, k, n);
    vk_run_matmul(c, pipeline, A_q8, a_blocks * Q8_0_BLOCK_BYTES, B, C_fill,
                  C_gpu, m, k, n);

    double max_abs = 0.0, max_rel = 0.0;
    for (uint32_t i = 0; i < m * n; i++) {
        double err = fabs((double)C_gpu[i] - (double)C_ref[i]);
        double denom = fabs((double)C_ref[i]) > 1e-6 ? fabs((double)C_ref[i]) : 1.0;
        if (err > max_abs)
            max_abs = err;
        if (err / denom > max_rel)
            max_rel = err / denom;
    }

    int pass = max_rel < 1e-2;
    printf("matmul_q8_0 %3ux%-3ux%-3u : max_abs_err=%.3g max_rel_err=%.3g -> %s\n",
           m, k, n, max_abs, max_rel, pass ? "PASS" : "FAIL");

    free(A_f32); free(A_q8); free(B); free(C_gpu); free(C_ref); free(C_fill);
    return pass;
}

int main(void)
{
    g_rng_state = 0x5EED1234567890ABULL;

    struct vk_ctx c;
    vk_ctx_init(&c);

    /* vkCreateComputePipelines validates the hand-assembled SPIR-V. */
    VkPipeline pipe_f32 = vk_create_pipeline(&c, vk_spv_matmul_f32,
                                             vk_spv_matmul_f32_word_count);
    printf("pipeline matmul_f32: created OK (%u words)\n",
           vk_spv_matmul_f32_word_count);
    VkPipeline pipe_q8 = vk_create_pipeline(&c, vk_spv_matmul_q8_0,
                                            vk_spv_matmul_q8_0_word_count);
    printf("pipeline matmul_q8_0: created OK (%u words)\n",
           vk_spv_matmul_q8_0_word_count);

    int pass = 1;
    /* odd sizes on purpose: exercises the m*n vs workgroup bounds check */
    pass &= test_matmul_f32(&c, pipe_f32, 37, 129, 23);
    pass &= test_matmul_f32(&c, pipe_f32, 64, 64, 64);
    pass &= test_matmul_f32(&c, pipe_f32, 1, 1, 1);
    pass &= test_matmul_f32(&c, pipe_f32, 128, 256, 96);
    pass &= test_matmul_q8_0(&c, pipe_q8, 33, 128, 17);
    pass &= test_matmul_q8_0(&c, pipe_q8, 64, 256, 64);
    pass &= test_matmul_q8_0(&c, pipe_q8, 1, 32, 1);
    pass &= test_matmul_q8_0(&c, pipe_q8, 100, 96, 100);

    printf("%s\n", pass ? "ALL TESTS PASSED" : "TESTS FAILED");
    return pass ? 0 : 1;
}
